## Is the name of the cluster
cluster_name: unknown
## The environment to use for the tenant cluster
environment: unknown
## The cloud vendor to use for the tenant cluster
cloud_vendor: unknown
## The features to enable in the tenant cluster
## i.e
## labels:
##   enable_argocd: "true"
##   enable_cert_manager: "true"
##   enable_ebs_driver: "true"
##   enable_efs_driver: "true"
##   enable_external_dns: "true"
##   enable_kyverno: "true"
##   enable_pod_identity: "true"
##   enable_external_secrets: "true"
labels: {}
## Annotations for the tenant cluster
annotations: {}
## The tenant repository for the tenant cluster
tenant_repository: unknown
## The revision of the tenant repository
tenant_revision: unknown
## The cost center to use for the tenant cluster
tenant_cost_center: unknown
## The platform repository for the tenant cluster
platform_repository: unknown
## The revision of the platform repository
platform_revision: unknown
## The path to the platform repository
platform_path: unknown
